services:
  - type: web
    name: djangosnippets
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangosnippets.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"
